---
# tasks file for helloworld

- name: Copying the application file
  copy:
    src: helloworld.js
    dest: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: 0644
  notify: restart helloworld

- name: Copying the systemd-service file
  copy:
    src: HelloWorld.service
    dest: /etc/systemd/system/HelloWorld.service
    owner: root
    group: root
    mode: 0644

- name: Make sure a service is running
  systemd:
    state: started
    name: HelloWorld